EshopWebApplication1/Controllers/AgenciesController.cs
using Eshop.DomainEntities;
using Eshop.DomainEntities.Domain;
using Eshop.Service.Implementation;
using Eshop.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EshopWebApplication1.Controllers
{
    public class AgenciesController : Controller
    {
        private readonly IAgencyService _agencyService;

        public AgenciesController(IAgencyService agencyService)
        {
            _agencyService = agencyService;
        }

        // GET: Agencies
        public IActionResult Index()
        {
            return View(_agencyService.GetAllAgencies());
        }

        // GET: Agencies/Details/Id
        public IActionResult Details(Guid? id)
        {
            var agency = _agencyService.GetDetailsForAgency(id);
            return View(agency);
        }

        // GET: Agencies/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Agency agency)
        {
            _agencyService.CreateNewAgency(agency);

            return RedirectToAction(nameof(Index));
        }

        // GET: Agencies/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var agency = _agencyService.GetDetailsForAgency(id);
            if (agency == null)
            {
                return NotFound();
            }
            return View(agency);
        }

        // POST: Agencies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Email,Phone,Address")] Agency agency)
        {
            if (id != agency.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _agencyService.UpdateExistingAgency(agency);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(agency);
        }

        // GET: Agencies/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agency = _agencyService.GetDetailsForAgency(id);
            if (agency == null)
            {
                return NotFound();
            }

            return View(agency);
        }

        // POST: Agencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var agency = _agencyService.GetDetailsForAgency(id);
            if (agency != null)
            {
                _agencyService.DeleteAgency(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EshopWebApplication1/Controllers/ItinerariesController.cs
using Eshop.DomainEntities.Domain;
using Eshop.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace EshopWebApplication1.Controllers
{
    public class ItinerariesController : Controller
    {
        private readonly IItineraryService itineraryService;
        private readonly ITravelPackageService travelPackageService;

        public ItinerariesController(ITravelPackageService travelPackageService,
            IItineraryService itineraryService)
        {
            this.travelPackageService = travelPackageService;
            this.itineraryService = itineraryService;
        }

        // GET: Itineraries
        public IActionResult Index()
        {
            return View(itineraryService.GetAllItineraries());
        }

        // GET: Itineraries/Details/Id
        public IActionResult Details(Guid? id)
        {
            var itinerary = itineraryService.GetDetailsForItinerary(id);
            return View(itinerary);
        }

        // GET: Itineraries/Create
        public IActionResult Create()
        {
            var travelPackages = travelPackageService.GetAllTravelPackages();
            ViewData["TravelPackageId"] = new SelectList(travelPackages, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Itinerary itinerary)
        {
            var result =  itineraryService.CreateNewItinerary(itinerary);
            if (result == true)
            {
                return RedirectToAction("Create", "PlannedRoutes", new { id = itinerary.Id });
            }
            return RedirectToAction("Error");

        }

        public IActionResult Error()
        {
            return View();
        }

        // GET: Itineraries/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var itinerary = itineraryService.GetDetailsForItinerary(id);
            if (itinerary == null)
            {
                return NotFound();
            }
            var travelPackages = travelPackageService.GetAllTravelPackages();
            ViewData["TravelPackageId"] = new SelectList(travelPackages, "Id", "Name");
            return View(itinerary);
        }

        // POST: Itineraries/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Itinerary itinerary)
        {
            if (id != itinerary.Id)
            {
                return NotFound();
            }
            itineraryService.UpdateExistingItinerary(itinerary);
            return RedirectToAction(nameof(Index));

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        itineraryService.UpdateExistingItinerary(itinerary);
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        throw;
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            //return View(itinerary);
        }

        // GET: Itineraries/Delete/5
        public async Task<IActionResult> Delete(Guid Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var itinerary = itineraryService.GetDetailsForItinerary(Id);
            if (itinerary == null)
            {
                return NotFound();
            }

            return View(itinerary);
        }

        // POST: Itineraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid Id)
        {
            var itinerary = itineraryService.GetDetailsForItinerary(Id);
            if (itinerary != null)
            {
                itineraryService.DeleteItinerary(Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EshopWebApplication1/Controllers/PetAdoptionCenter/PetsController.cs
using Eshop.DomainEntities.PetAdoptionCenter;
using Eshop.Service.PetAdoptionCenter.Interface;
using Microsoft.AspNetCore.Mvc;



namespace EshopWebApplication1.Controllers.PetAdoptionCenter
{
    public class PetsController : Controller
    {
        private readonly IPetsService petsService;

        public PetsController(IPetsService petsService)
        {
            this.petsService = petsService;
        }

        public IActionResult Index()
        {

            HttpClient client = new HttpClient();

            string URL = "https://petadoptioncenterapplication.azurewebsites.net/api/PacAdmin/ListAllPets";

            HttpResponseMessage response = client.GetAsync(URL).Result;

            var data = response.Content.ReadAsAsync<List<Pet>>().Result;
            for (int i = 0; i < data.Count(); i++)
            {
                Pet pet = data[i];
                petsService.CreateNewPet(pet);

            }
            List<Pet> allPets = petsService.GetAllPets();
            return View(allPets);
        }
    }
}

EshopWebApplication1/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EshopWebApplication1.Data;
using Eshop.DomainEntities;
using System.Security.Claims;
using Eshop.Service.Interface;
using Eshop.DomainEntities.Domain;
using Microsoft.AspNetCore.Authorization;

namespace EshopWebApplication1.Controllers
{
    public class TravelPackagesController : Controller
    {
        private readonly ITravelPackageService _travelPackageService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IItineraryService _itineraryService;
        private readonly IPlannedRouteService _plannedRouteService;
        private readonly IAgencyService _agencyService;

        public TravelPackagesController(ITravelPackageService? productService, 
            IShoppingCartService? shoppingCartService,
             IItineraryService itineraryService,
             IPlannedRouteService plannedRouteService,
            IAgencyService agencyService)
        {
            _travelPackageService = productService;
            _shoppingCartService = shoppingCartService;
            _itineraryService = itineraryService;
            _plannedRouteService = plannedRouteService;
            _agencyService = agencyService;

        }

        // GET: TravelPackages
        public IActionResult Index()
        {
            return View(_travelPackageService.GetAllTravelPackages());
        }

        // GET: TravelPackages/Details/5
        public IActionResult Details(Guid? id)
        {
            var travelPackage = _travelPackageService.GetDetailsForTravelPackage(id);
            var itinerary = _itineraryService.GetItineratyForTravelPackage(id);
          
            ViewBag.Itinerary = itinerary;

            return View(travelPackage);
        }

        // GET: TravelPackages/Create
        public IActionResult Create()
        {
            List<Agency> agencies = _agencyService.GetAllAgencies();
            ViewData["AgencyId"] = new SelectList(agencies, "Id", "Name");
            return View();
        }

        // POST: TravelPackages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TravelPackage travelPackage)
        {
            //if (!ModelState.IsValid)
            //{ 
            //    return View(travelPackage);
            //}
            _travelPackageService.CreateNewTravelPackage(travelPackage);
            
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> AddToCartConfirmed(TravelPackageInShoppingCart model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
            _shoppingCartService.AddToShoppingConfirmed(model, userId);
            return View("Index", _travelPackageService.GetAllTravelPackages());
        }

        [Authorize]
        public async Task<IActionResult> AddToCart(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var travelPackage = _travelPackageService.GetDetailsForTravelPackage(id);
            TravelPackageInShoppingCart ps = new TravelPackageInShoppingCart();
            ps.TravelPackageId = travelPackage.Id;
            return View(ps);
        }

        // GET: TravelPackages/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            List<Agency> agencies = _agencyService.GetAllAgencies();
            ViewData["AgencyId"] = new SelectList(agencies, "Id", "Name");
            var travelPackage =  _travelPackageService.GetDetailsForTravelPackage(id);
            if (travelPackage == null)
            {
                return NotFound();
            }
            return View(travelPackage);
        }

        // POST: TravelPackage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Price,Description,ImageTextBox,AgencyId,AlreadyhasItineraryF")] TravelPackage travelPackage)
        {
            if (id != travelPackage.Id)
            {
                return NotFound();
            }
            _travelPackageService.UpdeteExistingTravelPackage(travelPackage);
            return RedirectToAction(nameof(Index));

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        _travelPackageService.UpdeteExistingTravelPackage(travelPackage);
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        throw;
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            //return View(travelPackage);
        }

        // GET: TravelPackage/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = _travelPackageService.GetDetailsForTravelPackage(id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            return View(travelPackage);
        }

        // POST: TravelPackage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var travelPackage = _travelPackageService.GetDetailsForTravelPackage(id);
            if (travelPackage != null)
            {
                _travelPackageService.DeleteTravelPackage(id);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

EshopWebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EshopWebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EshopWebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 shadow-sm mb-2">
            <div class="container">
                <a class="navbar-brand fw-bold text-uppercase" asp-area="" asp-controller="Home" asp-action="Index">PVSTravel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TravelPackages" asp-action="Index">Travel Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agencies" asp-action="Index">Agencies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Itineraries" asp-action="Index">All Itineraries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCarts" asp-action="Index">My Wishlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">See our partner "Pet Adoption Center"</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark text-white text-center py-4 mt-5">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5>About Us</h5>
                    <p>We offer the best travel packages to help you explore the world. Join us on your next adventure!</p>
                </div>
                <div class="col">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Home</a></li>
                        <li><a href="/TravelPackages" class="text-white">Packages</a></li>
                        <li><a href="#" class="text-white">Contact Us</a></li>
                        <li><a href="#" class="text-white">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <hr class="bg-light">
            <p class="mb-0">&copy; 2024 - Your Travel Company. All Rights Reserved.</p>
            <p>Developed by Slavko, Predrag, and Vladimir</p>
        </div>
    </footer>

    <!-- FontAwesome icons (add this to your layout or header) -->
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>